### PR TITLE
changed reddit post to SSR

### PR DESCRIPTION
**Pull request by judgemavi**
Changed reddit post to be server rendered. This should improve performance as we are no longer waiting for client side to fetch post and render.

Also implemented suspense state properly

### CODE REVIEW

**Comment by erin-fitzpatric** [comment]
image

**Comment by erin-fitzpatric** [comment]
The Reddit API has been on the fritz - so make sure you account for when a weird or no response is received from the API

**Comment by erin-fitzpatric** [comment]
In the case that the posts do fail to load, the default behavior should be that the "loading" skeleton should remain rather than hiding the component all together. This is the current behavior in prod, from the preview, it wasn't looking like this would be the case. Wanted to check with you before merging.

If you have any idea why the posts are failing to return, I am not entirely sure why this is even happening in the first place. I'm hoping the caching will solve it.

**Comment by judgemavi** [comment]
pushed a change so skelton is shown if reddit post failed to pull. 

as for why its failing, could you share the logs with me by any change. When I run it locally it seems to work ok.

**Comment by erin-fitzpatric** [comment]
> pushed a change so skelton is shown if reddit post failed to pull
> 
> as for why its failing, could you share the logs with me by any change. When I run it locally it seems to work ok.

```
Error: Failed to fetch reddit posts: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at i (/var/task/.next/server/app/page.js:23:83560)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
    at async rT (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:8148)
    at async ne (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)
    at async es (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25944)
    at async en.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1026)
    at async r6.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:508)
    at async r6.renderPageComponent (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5085)
    at async r6.renderToResponseImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5663) {
  digest: '2654372716'
}
```

It just appears to be returning HTML when there is some kind of error.

**Comment by judgemavi** [comment]
i added user-agent just in case if that was the case. also any way I can access the preview link?

**Comment by erin-fitzpatric** [comment]
Unfortunately not without buying a seat in vercel which is $20 a month 😭

**Comment by judgemavi** [comment]
lol we could switch to aws down the road. its more hands on but cheaper and access to more services.

Also doesnt cost any money to collaborate. Fun fact vercel just resell aws

**Comment by erin-fitzpatric** [comment]
I'll pull this down locally and test tomorrow.

**Pull request merged**
