### PR TITLE
Implement Shadcn Nav Menu

### PR DESCRIPTION
**Pull request by kinsyudev**
Implementation of Issue #92.

All navigation is configured through the `navigation` array.

Feel free to change the icons if you think others are more fitting.

### CODE REVIEW

**Comment by kinsyudev** [comment]
Just finished implementing this, please take a look whenever you get a chance. I added a Sheet for mobile navigation, if you'd like a different approach, lmk.

**Review by erin-fitzpatric — CHANGES_REQUESTED** [review]
Looks great overall, thanks for picking this up! A few changes :

- Could the font and logo size be increased for the navbar? Maybe it needs more font weight too...just need to standout more. They look to small to me right now. I'm a big fan of the size they use here:
https://aoe4world.com/
- the social links are missing now. Could you add those back in? 
  - twitch
  - discord
  - kofi

**Comment by gijs-ve** [comment]
image
I think the wrapper for the 3 pages ("gods", "matchups", "maps") would look a little bit better if it were exactly the same width as the wrapper for the "statistics" collapsible (those couple of pixels to the right).

**Comment by erin-fitzpatric** [comment]
> image I think the wrapper for the 3 pages ("gods", "matchups", "maps") would look a little bit better if it were exactly the same width as the wrapper for the "statistics" collapsible (those couple of pixels to the right).

This will likely need to be expanded too because there will be more stats. Here is how aoe4 world does theirs:
image

One styling thing:
- I would prefer to have the header background black instead of the card gray background it has in the PR

**Comment by erin-fitzpatric** [comment]
Can they all get the same highlight that the statistics button does when you hover? I like the depth.

**Comment by erin-fitzpatric** [comment]
@kinsyudev - were you planning on continuing with this PR?

**Review by erin-fitzpatric — APPROVED** [review]

**Comment by erin-fitzpatric** [comment]
Haven't heard back from @kinsyudev , going to go ahead and merge this changes in and make a few tweaks. Need the new nav bar to support stats that were just launched. Feel free to open a new PR and cleanup the rest.

**Pull request merged**
